# Generated by Django 2.2 on 2021-01-26 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=150)),
                ('location', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'verbose_name': 'church',
                'verbose_name_plural': 'churches',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'contactMessage',
                'verbose_name_plural': 'contactmessages',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('detail', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='church')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('body_text', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='church')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=65)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.Profile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('topic', models.CharField(max_length=200)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchaccounts.Church')),
                ('participants', models.ManyToManyField(blank=True, to='user_profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1000)),
                ('timeframe', models.CharField(max_length=150)),
                ('Fundraiser', models.TextField(max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=65)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchaccounts.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('head', models.CharField(max_length=150)),
                ('timeframe', models.CharField(db_index=True, max_length=200)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchaccounts.Church')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250)),
                ('head_elder', models.CharField(max_length=200)),
                ('ch_pastor', models.CharField(max_length=200)),
                ('ch_clerk', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='churchaccounts.Church')),
            ],
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['id', 'slug'], name='churchaccou_id_c41907_idx'),
        ),
    ]
